### ISSUE TITLE
Does not seem to work anymore on Webkit (Chrome, Safari)

### ISSUE THREAD

**Issue by clst** [spencertipping/jquery.fix.clone#1]
My code just stopped working on Chrome and Safari.
Obviously something was changed in Webkit. The jQuery version I am using is still 1.7.1 not from the CDN.
I tried with 1.7.2 but no chance.

It still works fine in Opera.

Can someone verify/comment?

**Comment by clst** [comment]
Funny enough this still works after the clone:

``` javascript
$("#new_textarea").val($("#old_textarea").val())
```

I didn't have time to look further into it. This is what I used as workaround until I have more time.

**Comment by spencertipping** [comment]
Interesting, did it produce an error?

**Comment by spencertipping** [comment]
Oh never mind, I just found the problem. Sorry about that. It should work now.

**Comment by clst** [comment]
Thanks, that did it :)
